name = "InformalDAX"
uuid = "0ebbac5f-bd26-46aa-97ed-dcdb059fd87d"
authors = ["C. Naaktgeboren <NaaktgeborenC.PhD@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Currencies = "0fd90b74-7c1f-579e-9252-02cd883047b9"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FixedPointDecimals = "fb4d412d-6eee-574d-9565-ede6634db7b0"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Crayons = "4.1.1"
Currencies = "0.17.0"
Dates = "1.11.0"
FixedPointDecimals = "0.6.3"
Printf = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
